### ISSUE TITLE
Content migration fails with "This slug is already in use"

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1208]
The content migration for the South Asia site failed with the following exception:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/iogt_content_migration/management/commands/load_v1_db.py", line 102, in handle
    self.migrate(root)
  File "/app/iogt_content_migration/management/commands/load_v1_db.py", line 178, in migrate
    self.fix_articles_body()
  File "/app/iogt_content_migration/management/commands/load_v1_db.py", line 1699, in fix_articles_body
    v2_article.save()
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models.py", line 1010, in save
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models.py", line 976, in full_clean
    super().full_clean(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1231, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'slug': ['This slug is already in use']}
```

**Comment by istride** [comment]
Looking in the V1 database revealed the following pages with identical slugs.

```
select id, slug, title, live from wagtailcore_page where slug in (select slug from wagtailcore_page group by slug having count(*) > 1) order by slug;
 id  |        slug        |       title        | live 
-----+--------------------+--------------------+------
 130 | module-2b          | Module 2           | t
 132 | module-2b          | Module 2           | t
 120 | module-3           | Module 3           | t
 117 | module-3           | Module 3           | t
 113 | module-4           | Module 4           | t
 116 | module-4           | Module 4           | t
 111 | module-5           | Module 5           | t
 100 | module-5           | Module 5           | t
 104 | module-6           | Module 6           | t
  96 | module-6           | Module 6           | t
 102 | post-test-module-5 | Post-Test Module 5 | t
 109 | post-test-module-5 | Post-Test Module 5 | t
  98 | post-test-module-6 | Post-Test Module 6 | t
 107 | post-test-module-6 | Post-Test Module 6 | t
 108 | pre-test-module-5  | Pre-Test Module 5  | t
 101 | pre-test-module-5  | Pre-Test Module 5  | t
 106 | pre-test-module-6  | Pre-Test Module 6  | t
  95 | pre-test-module-6  | Pre-Test Module 6  | t
 105 | surveys-quizzes    | Surveys & Quizzes  | f
  97 | surveys-quizzes    | Surveys & Quizzes  | f
(20 rows)
```

**Comment by istride** [comment]
@sheralim012 As requested, same info as above with 'url_path' column included.

```
select id, slug, url_path, title, live from wagtailcore_page where slug in (select slug from wagtailcore_page group by slug having count(*) > 1) order by slug, url_path;                                                                                                                                                                     
 id  |        slug        |                                      url_path                                       |       title        | live 
-----+--------------------+-------------------------------------------------------------------------------------+--------------------+------
 132 | module-2b          | /home/sections/who-health-worker-covax-Text/module-2b/                              | Module 2           | t
 130 | module-2b          | /home/sections/who-health-worker-covax-training/module-2b/                          | Module 2           | t
 120 | module-3           | /home/sections/who-health-worker-covax-Text/module-3/                               | Module 3           | t
 117 | module-3           | /home/sections/who-health-worker-covax-training/module-3/                           | Module 3           | t
 116 | module-4           | /home/sections/who-health-worker-covax-Text/module-4/                               | Module 4           | t
 113 | module-4           | /home/sections/who-health-worker-covax-training/module-4/                           | Module 4           | t
 111 | module-5           | /home/sections/who-health-worker-covax-Text/module-5/                               | Module 5           | t
 100 | module-5           | /home/sections/who-health-worker-covax-training/module-5/                           | Module 5           | t
 104 | module-6           | /home/sections/who-health-worker-covax-Text/module-6/                               | Module 6           | t
  96 | module-6           | /home/sections/who-health-worker-covax-training/module-6/                           | Module 6           | t
 109 | post-test-module-5 | /home/sections/who-health-worker-covax-Text/surveys-quizzes/post-test-module-5/     | Post-Test Module 5 | t
 102 | post-test-module-5 | /home/sections/who-health-worker-covax-training/surveys-quizzes/post-test-module-5/ | Post-Test Module 5 | t
 107 | post-test-module-6 | /home/sections/who-health-worker-covax-Text/surveys-quizzes/post-test-module-6/     | Post-Test Module 6 | t
  98 | post-test-module-6 | /home/sections/who-health-worker-covax-training/surveys-quizzes/post-test-module-6/ | Post-Test Module 6 | t
 108 | pre-test-module-5  | /home/sections/who-health-worker-covax-Text/surveys-quizzes/pre-test-module-5/      | Pre-Test Module 5  | t
 101 | pre-test-module-5  | /home/sections/who-health-worker-covax-training/surveys-quizzes/pre-test-module-5/  | Pre-Test Module 5  | t
 106 | pre-test-module-6  | /home/sections/who-health-worker-covax-Text/surveys-quizzes/pre-test-module-6/      | Pre-Test Module 6  | t
  95 | pre-test-module-6  | /home/sections/who-health-worker-covax-training/surveys-quizzes/pre-test-module-6/  | Pre-Test Module 6  | t
 105 | surveys-quizzes    | /home/sections/who-health-worker-covax-Text/surveys-quizzes/                        | Surveys & Quizzes  | f
  97 | surveys-quizzes    | /home/sections/who-health-worker-covax-training/surveys-quizzes/                    | Surveys & Quizzes  | f
(20 rows)

```

**Comment by cbunicef** [comment]
@istride @sheralim012 Hi both, how is this coming along? Any estimates on when it might be resolved?

**Comment by sheralim012** [comment]
wagtail doesn't enforce the unique constraint on database level and only enforce it on view level
somehow in V1 multiple pages were created/updated to have the same slug 
the reason these pages are still accessible is that they have different URLs 

the solution is to check if the slug is available or needs to be amended before trying to create the page (this is what wagtail does right now)
@istride are you ok with this approach?
