### ISSUE TITLE
Features to add to Surveys

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#156]
Front-end:
- [x] Support for URL input fields. Currently, they don't appear
- [x] When input type "checkbox" is set as "required" in the backend, when submitting, the error message "This field is required." is displayed regardless of whether it is checked or not, making it impossible to complete the survey.
- [x] Support for "(single) Checkbox" fields. They currently crash the page.
- [x] Support for "multiple select" fields. The selected options currently don't display properly.
- [x] Bugfix: If there are multiple "dropdown"/"multiple select" fields on a single page, clicking on a lower one will show the options from the first one.
- [x] Bugfix: If there are multiple "checkboxes" fields on a single page, clicking on an option (i.e. the text, not the checkbox itself) from a lower one will check/uncheck the corresponding option for the first one.
- [x] Bugfix: required text fields are currently marked with the tag "optional"
- [x] Bugfix: When receiving a validation error (e.g. empty required field), and being redirected to the same page of the questionnaire, the numbering of questions is wrong (e.g. Question 2 of 1)
- On the first page of a survey/quiz/poll, the "Back" button takes you to the home page rather than back to the article/section you came from. Now #359
- [x] When input type "checkbox" is set as "required" in the backend, the info text is "CHECK ALL THAT APPLY". 

Backend:
- [x] Bugfix: In the admin interface, "Answer options" is a required field (should have at least one entry, otherwise a validation error occurs when trying to save). However, when saving a question with text/number/etc input, "Answer options" for such fields is erased. I believe it shouldn't be a required field for these input types, or maybe not be available at all? Also see #301 
- Implement temp fix for #315 by disabling answer options for input type "checkbox"
- [x] Page breaks need to functional when surveys are published
- [x] Skip logic needs to be functional when surveys are published
- [x] Support _Positive Number_ in addition to _Number_ input type. Positive Number has 0 as the minimum.
- [x] Support for anonymous submission (if specified in the backend).

**Comment by ehmadzubair** [comment]
I'm starting work on this ticket

**Comment by geoo89** [comment]
Crash log for "checkbox" input type as of commit 948d8a2:
This is for a survey with a single checkbox.

Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/en/sections/youth/the-survey/

Django Version: 3.1.11
Python Version: 3.6.9
Installed Applications:
['home',
 'search',
 'iogt_users',
 'comments',
 'iogt_content_migration',
 'questionnaires',
 'messaging',
 'django.contrib.humanize',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailmedia',
 'wagtailmarkdown',
 'wagtail_transfer',
 'wagtailsvg',
 'wagtail.contrib.settings',
 'django_comments_xtd',
 'django_comments',
 'modelcluster',
 'taggit',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'sass_processor',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'iogt_users.middlewares.RegistrationSurveyRedirectMiddleware',
 'external_links.middleware.RewriteExternalLinksMiddleware']


Template error:
In template /data/idems/iogt/iogt/questionnaires/templates/questionnaires/tags/checkboxes.html, error at line 8
   label
   1 : {% load static wagtailcore_tags wagtailimages_tags %}
   2 : 
   3 : {% for ckeckbox in field %}
   4 :     <div class="quest-item__content">
   5 :         <label class="cust-check cust-check--2 quest-item__input">
   6 :             <input type="{{ field.field.widget.input_type }}"
   7 :                    name="{{ field.name }}"
   8 :                    value=" {{ ckeckbox.choice_label }} ">
   9 :             <div class="cust-check__title">
   10 :                 <span class="cust-check__check"></span>
   11 :                 <span>{{ ckeckbox.choice_label }}</span>
   12 :             </div>
   13 :         </label>
   14 :     </div>
   15 : {% endfor %}
   16 : 

Traceback (most recent call last):
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]

During handling of the above exception ('BoundWidget' object is not subscriptable), another exception occurred:
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/forms/boundfield.py", line 274, in choice_label
    return self.data['label']

Exception Type: KeyError at /en/sections/youth/the-survey/
Exception Value: 'label'
