### ISSUE TITLE
Page breaks crash quizzes/surveys

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#354]
If multi-step is enabled, each question is on a new page, and everything works fine (manual page breaks are ignored).

If multi-step is disabled, and a manual page break is inserted somewhere in a quiz/survey, the page crashes.

Should be fixed or disabled (I don't see page breaks in the requirements, but I'm not sure).

**Comment by geoo89** [comment]
Environment:


Request Method: GET
Request URL: http://iogt-django-dev.idems.international/en/sections/questionnaire-testing/skip-logic/quiz-manual-page-breaks/

Django Version: 3.1.12
Python Version: 3.6.9
Installed Applications:
['home',
 'search',
 'iogt_users',
 'comments',
 'iogt_content_migration',
 'questionnaires',
 'messaging',
 'django.contrib.humanize',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailmedia',
 'wagtailmarkdown',
 'wagtail_transfer',
 'wagtailsvg',
 'wagtail.contrib.settings',
 'django_comments_xtd',
 'django_comments',
 'modelcluster',
 'taggit',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'sass_processor',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'iogt_users.middlewares.RegistrationSurveyRedirectMiddleware',
 'external_links.middleware.RewriteExternalLinksMiddleware']


Template error:
In template /home/georg/iogt/iogt/templates/base.html, error at line 0
   'str' object has no attribute 'paginator'
   1 : {% load static wagtailuserbar home_tags sass_tags wagtailsettings_tags menu_tags %}
   2 : {% get_settings %}
   3 : 
   4 : <!DOCTYPE html>
   5 : <html class="no-js" lang="en">
   6 : <head>
   7 :     <script async src="https://www.googletagmanager.com/gtag/js?id={{ settings.home.SiteSettings.local_ga_tracking_code }}"></script>
   8 :     <script>
   9 :         window.dataLayer = window.dataLayer || [];
   10 :         function gtag(){window.dataLayer.push(arguments);}


Traceback (most recent call last):
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/georg/iogt_venv/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/georg/iogt/questionnaires/templatetags/questionnaires_tags.py", line 72, in field_counter
    total = fields_step.paginator.count

Exception Type: AttributeError at /en/sections/questionnaire-testing/skip-logic/quiz-manual-page-breaks/
Exception Value: 'str' object has no attribute 'paginator'

**Comment by sheralim012** [comment]
@geoo89 as far as I know, this was discussed before and multi-step and page break work together or not at all

- if page break is enabled for any question and multi-step is disabled then it will crash
- I think a simple solution to this is to add a validation check to enable multi-step if page break is enabled for at least one question (#377 )
