### ISSUE TITLE
Homepage crash

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#917]
When switching the language of the KE migration to Swahili, the site crashes: https://ke.iogt.site/sw/

```
Environment:


Request Method: GET
Request URL: http://ke.iogt.site/sw/

Django Version: 3.1.14
Python Version: 3.8.1
Installed Applications:
['home',
 'search',
 'iogt_users',
 'comments',
 'iogt_content_migration',
 'questionnaires',
 'messaging',
 'django.contrib.humanize',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailmedia',
 'wagtailmarkdown',
 'wagtail_transfer',
 'wagtailsvg',
 'wagtail.contrib.settings',
 'django_comments_xtd',
 'django_comments',
 'modelcluster',
 'taggit',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'sass_processor',
 'translation_manager',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'iogt_users.middlewares.RegistrationSurveyRedirectMiddleware',
 'external_links.middleware.RewriteExternalLinksMiddleware',
 'iogt.middleware.CacheControlMiddleware']


Template error:
In template /app/questionnaires/templates/questionnaires/tags/questionnaire_wrapper.html, error at line 6
   list index out of range
   1 : {% load generic_components %}
   2 : {% load static wagtailcore_tags i18n questionnaires_tags %}
   3 : 
   4 : {% if direct_display %}
   5 :     <div style="padding-bottom: 10px">
   6 :          {% render_questionnaire_form page %} 
   7 :     </div>
   8 : {% else %}
   9 :     {% render_questionnaire_card page=page background_color=background_color font_color=font_color %}
   10 : {% endif %}
   11 : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/templatetags/wagtailcore_tags.py", line 134, in render
    output = value.render_as_block(context=new_context)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/stream_block.py", line 522, in render_as_block
    return self.stream_block.render(self, context=context)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/base.py", line 265, in render
    return self.render_basic(value, context=context)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/stream_block.py", line 334, in render_basic
    [
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/stream_block.py", line 335, in <listcomp>
    (child.render(context=context), child.block_type)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/base.py", line 456, in render
    return self.block.render(self.value, context=context)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/base.py", line 272, in render
    return mark_safe(render_to_string(template, new_context))
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/app/questionnaires/templatetags/questionnaires_tags.py", line 96, in render_questionnaire_form
    step = paginator.page(1)
  File "/app/questionnaires/utils.py", line 142, in page
    top = self.page_breaks[top_index]

Exception Type: IndexError at /sw/
Exception Value: list index out of range
```

**Comment by sheralim012** [comment]
this is happening because home page has a survey `/sw/surveys/swahili-translation-of-take-a-quick-survey/` with no form field, handling this case now

**Comment by cbunicef** [comment]
Very strange, now that I've unpublished the SW language homepage it is still available and loading fine. https://ke.iogt.site/sw/

**Comment by sheralim012** [comment]
<img width="587" alt="Screenshot 2021-12-17 at 11 09 02 AM" src="https://user-images.githubusercontent.com/49383675/146497593-1fdbb1d2-9048-4c2e-8b78-568bbeb8c747.png">

this issue occurs when direct display (embedded view instead of card view) is on for featured questionnaire with no form field

currently, the live site is rendering it as a card so the issue is not occurring, once you on the direct display flag the issue will occur again
